
import "./globals.css";
import { GlobalProvider } from "./context/context";
import Header from "./components/header/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalProvider>
      <body>
        <Header></Header>
        {children}
      </body>
    </GlobalProvider>
      
    </html>
  );
}
